structure(list(url = "https://api.todoist.com/rest/v1/projects", 
    status_code = 500L, headers = structure(list(`content-type` = "text/plain; charset=utf-8", 
        `content-length` = "22", connection = "keep-alive", date = "Sun, 04 Aug 2019 22:47:09 GMT", 
        `x-content-type-options` = "nosniff", `x-cache` = "Error from cloudfront", 
        via = "1.1 71b4286865a66a104e8b17e67191033e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "SYD4-C1", `x-amz-cf-id` = "pnKpeH-QVMxXsrt_1G0mb22UG_upTEVc7g21CNK1G40xMG43SzNsbw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 500L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "text/plain; charset=utf-8", 
            `content-length` = "22", connection = "keep-alive", 
            date = "Sun, 04 Aug 2019 22:47:09 GMT", `x-content-type-options` = "nosniff", 
            `x-cache` = "Error from cloudfront", via = "1.1 71b4286865a66a104e8b17e67191033e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "SYD4-C1", `x-amz-cf-id` = "pnKpeH-QVMxXsrt_1G0mb22UG_upTEVc7g21CNK1G40xMG43SzNsbw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Internal Server Error\n"), date = structure(1564958829, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.7e-05, pretransfer = 8.3e-05, starttransfer = 0.224111, 
    total = 0.224149)), class = "response")
