structure(list(url = "https://api.todoist.com/rest/v1/projects", 
    status_code = 500L, headers = structure(list(`content-type` = "text/plain; charset=utf-8", 
        `content-length` = "22", connection = "keep-alive", date = "Sun, 04 Aug 2019 03:13:11 GMT", 
        `x-content-type-options` = "nosniff", `x-cache` = "Error from cloudfront", 
        via = "1.1 b06a46f10d78708d3fc53da3a078c92d.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "SYD1-C2", `x-amz-cf-id` = "UaJRDjtPm_KieF_eqxKYxgilDznO3ui4co0nqWW4s_S2CAnBX9OAzg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 500L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "text/plain; charset=utf-8", 
            `content-length` = "22", connection = "keep-alive", 
            date = "Sun, 04 Aug 2019 03:13:11 GMT", `x-content-type-options` = "nosniff", 
            `x-cache` = "Error from cloudfront", via = "1.1 b06a46f10d78708d3fc53da3a078c92d.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "SYD1-C2", `x-amz-cf-id` = "UaJRDjtPm_KieF_eqxKYxgilDznO3ui4co0nqWW4s_S2CAnBX9OAzg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Internal Server Error\n"), date = structure(1564888391, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.4e-05, 
    connect = 2.5e-05, pretransfer = 6.6e-05, starttransfer = 0.831035, 
    total = 0.831053)), class = "response")
